### PR TITLE
#bz-1592853 added option --batch for unattended mode

### PR DESCRIPTION
**Pull request by knumskull**
To fulfil request of https://bugzilla.redhat.com/show_bug.cgi?id=1592853, I've added option --batch to comply with sosreport

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
Thanks for having contributed this patch! Please note that this GitHub repository is a backup only repository. It's automatically synchronized from gerrit.ovirt.org so merging patches here will cause them to be reverted on next synchronization. Can you please push this patch to gerrit? Project page is at https://gerrit.ovirt.org/#/admin/projects/ovirt-log-collector
If you can't, I can push it on your behalf, let me know.

**Comment by knumskull** [comment]
How can I push to gerrit? Do I need some access? Is there a documentation available, how to contribute?
I'm happy to do it the right way.

**Comment by sandrobonazzola** [comment]
@knumskull yes, you need to be registered on https://gerrit.ovirt.org/ you can follow https://www.ovirt.org/develop/dev-process/working-with-gerrit.html

**Comment by sandrobonazzola** [comment]
Merged in https://gerrit.ovirt.org/#/c/97298/

**Pull request closed without merging**
